# Generated by Django 3.2.9 on 2022-04-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('file', models.FileField(upload_to='wavs/')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('octave', models.IntegerField(default=0)),
                ('oscParam1', models.IntegerField(default=0)),
                ('oscParam2', models.IntegerField(default=0)),
                ('lfoSpeed', models.IntegerField(default=0)),
                ('lfoval', models.IntegerField(default=0)),
                ('Attack', models.IntegerField(default=0)),
                ('Decay', models.IntegerField(default=0)),
                ('Sustain', models.IntegerField(default=0)),
                ('Release', models.IntegerField(default=0)),
                ('Effect1', models.IntegerField(default=0)),
                ('Effect2', models.IntegerField(default=0)),
                ('oscType', models.IntegerField(default=0)),
                ('effectType', models.IntegerField(default=0)),
                ('lfoTarget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image', models.BinaryField(blank=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fileshare.configmodel')),
            ],
        ),
    ]
