# Generated by Django 3.2.9 on 2021-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('octave', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pulseWidth', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pwmFreq', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pwmValue', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attack', models.DecimalField(decimal_places=2, max_digits=3)),
                ('decay', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sustain', models.DecimalField(decimal_places=2, max_digits=3)),
                ('release', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
