# Generated by Django 3.2.9 on 2021-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_configmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigModel',
            new_name='SynthModel',
        ),
    ]
