# Generated by Django 3.2.9 on 2021-11-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_rename_configmodel_synthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthmodel',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
