# Generated by Django 3.2.9 on 2021-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_alter_synthmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiomodel',
            old_name='file_field',
            new_name='file',
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
