# Generated by Django 3.2.9 on 2022-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0006_auto_20211130_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthmodel',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='decay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='octave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='pulseWidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='pwmFreq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='pwmValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='release',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='sustain',
            field=models.IntegerField(default=0),
        ),
    ]
