# Generated by Django 3.2.9 on 2022-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0007_auto_20220118_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synthmodel',
            old_name='pulseWidth',
            new_name='cutoff',
        ),
        migrations.RenameField(
            model_name='synthmodel',
            old_name='pwmFreq',
            new_name='hp_lp',
        ),
        migrations.RenameField(
            model_name='synthmodel',
            old_name='pwmValue',
            new_name='oscParam1',
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='oscParam2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='oscParam3',
            field=models.IntegerField(default=0),
        ),
    ]
