# Generated by Django 3.2.9 on 2022-02-09 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0008_auto_20220127_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthmodel',
            name='waveForm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='attack',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='cutoff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='decay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='hp_lp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='octave',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='oscParam1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='oscParam2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='oscParam3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='release',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='sustain',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
    ]
