# Generated by Django 3.2.9 on 2022-02-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0009_auto_20220209_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthmodel',
            name='oscParam3',
        ),
    ]
