# Generated by Django 3.2.9 on 2022-02-24 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0010_remove_synthmodel_oscparam3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthmodel',
            name='attack',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='cutoff',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='decay',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='hp_lp',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='octave',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='oscParam1',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='oscParam2',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='release',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='sustain',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='waveForm',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
