# Generated by Django 3.2.9 on 2022-02-24 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0011_auto_20220224_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthmodel',
            name='cutoff',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='hp_lp',
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='fx_param1',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='fx_param2',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='fx_sel',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='lfo_speed',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='lfo_target',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='lfo_val',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127), django.core.validators.MinValueValidator(0)]),
        ),
    ]
