# Generated by Django 3.2.9 on 2022-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0014_remove_synthmodel_oscparam3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthmodel',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='decay',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='fx_param1',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='fx_param2',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='fx_sel',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='lfo_speed',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='lfo_target',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='lfo_val',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='octave',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='oscParam1',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='oscParam2',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='release',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='sustain',
        ),
        migrations.RemoveField(
            model_name='synthmodel',
            name='waveForm',
        ),
        migrations.AddField(
            model_name='synthmodel',
            name='synFile',
            field=models.FileField(null=True, upload_to='configs'),
        ),
        migrations.AlterField(
            model_name='audiomodel',
            name='file',
            field=models.FileField(upload_to='images'),
        ),
    ]
