# Generated by Django 3.2.9 on 2022-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0015_auto_20220331_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='file',
            field=models.FileField(upload_to='wavs'),
        ),
    ]
