# Generated by Django 3.2.9 on 2022-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0016_alter_audiomodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
