# Generated by Django 4.0.3 on 2022-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0017_synthmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='synFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
