# Generated by Django 4.0.3 on 2022-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0018_alter_synthmodel_photo_alter_synthmodel_synfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='synthmodel',
            name='synFile',
            field=models.FileField(upload_to=''),
        ),
    ]
