# Generated by Django 4.0.3 on 2022-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0019_alter_audiomodel_name_alter_synthmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('octave', models.IntegerField(default=0)),
                ('oscParam1', models.IntegerField(default=0)),
                ('oscParam2', models.IntegerField(default=0)),
                ('lfoSpeed', models.IntegerField(default=0)),
                ('lfoval', models.IntegerField(default=0)),
                ('Attack', models.IntegerField(default=0)),
                ('Decay', models.IntegerField(default=0)),
                ('Sustain', models.IntegerField(default=0)),
                ('Release', models.IntegerField(default=0)),
                ('Effect1', models.IntegerField(default=0)),
                ('Effect2', models.IntegerField(default=0)),
            ],
        ),
    ]
