# Generated by Django 4.0.3 on 2022-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0020_configmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='effectType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='lfoTarget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='oscType',
            field=models.IntegerField(default=0),
        ),
    ]
