# Generated by Django 4.0.3 on 2022-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0021_configmodel_effecttype_configmodel_lfotarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='image',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
