# Generated by Django 3.2.9 on 2022-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0022_configmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
