# Generated by Django 4.0.3 on 2022-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0022_configmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
