# Generated by Django 3.2.9 on 2022-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0023_alter_configmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
