# Generated by Django 4.0.3 on 2022-04-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0024_alter_audiomodel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SynthModel',
        ),
    ]
