# Generated by Django 3.2.9 on 2022-04-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0024_alter_configmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='image',
        ),
    ]
