# Generated by Django 4.0.3 on 2022-04-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0025_delete_synthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('name', models.CharField(max_length=16)),
                ('file', models.ImageField(upload_to='screens/')),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fileshare.configmodel')),
            ],
        ),
    ]
