# Generated by Django 4.0.3 on 2022-04-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0027_remove_imagemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
