# Generated by Django 4.0.3 on 2022-04-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0028_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
