# Generated by Django 3.2.9 on 2022-04-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0029_remove_imagemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='name',
        ),
    ]
